#application: tclh123
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/x-icon

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  
- url: /tinymce/.*
  script: zipserve.app

#- url: /tinymce
#  static_dir: tinymce  
  
- url: /static
  static_dir: static

- url: /rpc|/xmlrpc\.php|/rpc/.*
  script: micolog.api_rpc.app

- url: /themes/.*
  script: micolog.micolog_app

- url: /myadmin/.*|/myadmin
  script: google.appengine.ext.admin.application
  login: admin

- url: /admin/post|/admin/entries/(post|page)|/admin/links|/admin/categories|/admin/comments
  script: micolog.admin_app
  login: required

- url: /admin/{0,1}
  script: micolog.admin_app
  login: required

- url: /admin/link|/admin/category|/admin/(post|page)|/admin/lang|/admin/filemanager|/admin/upload|/admin/uploadex
  script: micolog.admin_app
  login: required

- url: /admin/.*
  script: micolog.admin_app
  login: admin
  
- url: /remote_api
  script: google.appengine.ext.remote_api.handler.application
  login: admin

- url: /.*
  script: micolog.micolog_app

libraries:
- name: webapp2
  version: latest
- name: django
  version: "1.2"
- name: PIL
  version: "1.1.7"
  
#builtins:
#- django_wsgi: on

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'
